Add I2C implementation
flynneva/bno055 pull request #52
Opened 2022-12-06 18:02 UTC by asymingt

This modifies the code to add I2C support for the BNO055 sensor using the `smbus` library for I2C access. It adds `i2c_bus` and `i2c_addr` parameters to define the bus and address for the chip. 

Tested on a Google Coral Dev Mini board.

```
[bno055-4] [INFO] [1670349295.067779214] [bno055_imu_node]: Initializing parameters
[bno055-4] [INFO] [1670349295.226606079] [bno055_imu_node]: Parameters set to:
[bno055-4] [INFO] [1670349295.237909569] [bno055_imu_node]: 	ros_topic_prefix:	"bno055/"
[bno055-4] [INFO] [1670349295.246089261] [bno055_imu_node]: 	connection_type:	"i2c"
[bno055-4] [INFO] [1670349295.254703418] [bno055_imu_node]: 	i2c_bus:		"0"
[bno055-4] [INFO] [1670349295.269453248] [bno055_imu_node]: 	i2c_addr:		"40"
[bno055-4] [INFO] [1670349295.288136576] [bno055_imu_node]: 	uart_port:		"/dev/ttyUSB0"
[bno055-4] [INFO] [1670349295.305530661] [bno055_imu_node]: 	uart_baudrate:		"115200"
[bno055-4] [INFO] [1670349295.312030337] [bno055_imu_node]: 	uart_timeout:		"0.1"
[bno055-4] [INFO] [1670349295.339739595] [bno055_imu_node]: 	frame_id:		"bno055"
[bno055-4] [INFO] [1670349295.346247194] [bno055_imu_node]: 	data_query_frequency:	"100"
[bno055-4] [INFO] [1670349295.381144366] [bno055_imu_node]: 	calib_status_frequency:	"0.1"
[bno055-4] [INFO] [1670349295.417296241] [bno055_imu_node]: 	operation_mode:		"12"
[bno055-4] [INFO] [1670349295.431217601] [bno055_imu_node]: 	placement_axis_remap:	"P2"
[bno055-4] [INFO] [1670349295.440816383] [bno055_imu_node]: 	acc_factor:		"100.0"
[bno055-4] [INFO] [1670349295.448194452] [bno055_imu_node]: 	mag_factor:		"16000000.0"
[bno055-4] [INFO] [1670349295.461348882] [bno055_imu_node]: 	gyr_factor:		"900.0"
[bno055-4] [INFO] [1670349295.469705729] [bno055_imu_node]: 	set_offsets:		"False"
[bno055-4] [INFO] [1670349295.477400878] [bno055_imu_node]: 	offset_acc:		"[65516, 165, 65512]"
[bno055-4] [INFO] [1670349295.487703359] [bno055_imu_node]: 	radius_acc:		"1000"
[bno055-4] [INFO] [1670349295.497006907] [bno055_imu_node]: 	offset_mag:		"[65460, 65182, 637]"
[bno055-4] [INFO] [1670349295.504581670] [bno055_imu_node]: 	radius_mag:		"0"
[bno055-4] [INFO] [1670349295.511741121] [bno055_imu_node]: 	offset_gyr:		"[2, 65535, 65535]"
[bno055-4] [INFO] [1670349295.520134199] [bno055_imu_node]: 	variance_acc:		"[0.017, 0.017, 0.017]"
[bno055-4] [INFO] [1670349295.527464729] [bno055_imu_node]: 	variance_angular_vel:	"[0.04, 0.04, 0.04]"
[bno055-4] [INFO] [1670349295.541111010] [bno055_imu_node]: 	variance_orientation:	"[0.0159, 0.0159, 0.0159]"
[bno055-4] [INFO] [1670349295.548788005] [bno055_imu_node]: 	variance_mag:		"[0.0, 0.0, 0.0]"
[bno055-4] [INFO] [1670349295.653781137] [bno055_imu_node]: Configuring device...
[bno055-4] [INFO] [1670349295.665464323] [bno055_imu_node]: Current sensor offsets:
[bno055-4] [INFO] [1670349295.679366299] [bno055_imu_node]: 	Accel offsets (x y z): 0 1 3
[bno055-4] [INFO] [1670349295.685914744] [bno055_imu_node]: 	Accel radius: 1000
[bno055-4] [INFO] [1670349295.692526114] [bno055_imu_node]: 	Mag offsets (x y z): 0 0 0
[bno055-4] [INFO] [1670349295.698720325] [bno055_imu_node]: 	Mag radius: 0
[bno055-4] [INFO] [1670349295.705520927] [bno055_imu_node]: 	Gyro offsets (x y z): 0 0 0
[bno055-4] [INFO] [1670349295.712171989] [bno055_imu_node]: Setting device_mode to 12
[bno055-4] [INFO] [1670349295.719500904] [bno055_imu_node]: Bosch BNO055 IMU configuration complete.
```

I do get two warnings about the first few readings being zero after initial configuration.

```
[bno055-4] [WARN] [1670349295.757589413] [bno055_imu_node]: Receiving sensor data failed with ZeroDivisionError:"float division by zero"
[rosbridge_websocket-1] [INFO] [1670349295.769806834] [rosbridge_server_node]: Rosbridge WebSocket server started on port 54321
[bno055-4] [WARN] [1670349295.786740146] [bno055_imu_node]: Receiving sensor data failed with ZeroDivisionError:"float division by zero"
```

IMU data looks to not be garbage:

![Screenshot from 2022-12-06 10-02-15](https://user-images.githubusercontent.com/37671/205987508-e492c7e1-4b40-4f45-8d53-bf4240948699.png)

2022-12-07 05:30 UTC, asymingt commented
> @asymingt hey hey this is awesome stuff! I try to carve some time out soon to review this and test the UART stuff.
> 
> So cool btw to hear this is working on a google coral board - haven't gotten one myself but they definitely look cool!

@flynneva, glad you appreciate the contribution. The code does work, but it's not particularly high-performance. I'm seeing ~60Hz throughput when the node is run without anything else:

```
root@red-umpire:~# ros2 topic hz /bno055/mag
average rate: 61.433
	min: 0.014s max: 0.017s std dev: 0.00088s window: 63
average rate: 61.174
	min: 0.014s max: 0.018s std dev: 0.00086s window: 124
average rate: 61.432
	min: 0.014s max: 0.018s std dev: 0.00090s window: 186
average rate: 61.537
	min: 0.014s max: 0.018s std dev: 0.00092s window: 248
average rate: 61.606
	min: 0.014s max: 0.018s std dev: 0.00092s window: 310
```

Also, the magnetic field sensor is somehow now also working, although I think the scale factor is off.

2022-12-07 17:24 UTC, asymingt commented
> > @asymingt hey hey this is awesome stuff! I try to carve some time out soon to review this and test the UART stuff.
> > So cool btw to hear this is working on a google coral board - haven't gotten one myself but they definitely look cool!
> 
> @flynneva, glad you appreciate the contribution. The code does work, but it's not particularly high-performance. I'm seeing ~60Hz throughput when the node is run without anything else:
> 
> ```
> root@red-umpire:~# ros2 topic hz /bno055/mag
> average rate: 61.433
> 	min: 0.014s max: 0.017s std dev: 0.00088s window: 63
> average rate: 61.174
> 	min: 0.014s max: 0.018s std dev: 0.00086s window: 124
> average rate: 61.432
> 	min: 0.014s max: 0.018s std dev: 0.00090s window: 186
> average rate: 61.537
> 	min: 0.014s max: 0.018s std dev: 0.00092s window: 248
> average rate: 61.606
> 	min: 0.014s max: 0.018s std dev: 0.00092s window: 310
> ```
> 
> Also, the magnetic field sensor is somehow now also working, although I think the scale factor is off.

These results are actually comparable to a pure C++ implementation (https://github.com/bdholt1/ros2_bno055_sensor) so I suspect this might have to do with (1) bus speed limitations, or (2) IPC overhead. I'm leaning towards the former.

2022-12-11 21:11 UTC, asymingt commented
Worked out that I am bus limited. Knowing this, I can get 100Hz raw IMU / 20Hz magnetometer with this PR, where I've separated our the publication into smaller i2c transactions. 

https://github.com/asymingt/bno055/pull/1/files#diff-37a67ff78eb7260214b323353263b9af40a2fa98719a1e81937fae0159df87a3

But I have to disable quaternion and gravitational vector publication:

```py
# For streaming raw inertial data.
Node(
    package='bno055',
    executable='bno055',
    name='bno055_imu_node',
    parameters=[
        { "ros_topic_prefix": "bno055/" },
        { "connection_type": "i2c" },
        { "i2c_bus": 0 },
        { "i2c_addr": 0x28 },
        { "imu_query_frequency": 100 },
        { "rot_query_frequency": 0 },
        { "gra_query_frequency": 0 },
        { "mag_query_frequency": 20 },
        { "tmp_query_frequency": 1 },
        { "cal_query_frequency": 1 },
        { "frame_id": "bno055" },
        { "operation_mode": 0x0C },
        { "placement_axis_remap": "P2" },
        { "acc_factor": 100.0 },
        { "mag_factor": 16000000.0 },
        { "gyr_factor": 900.0 },
        { "set_offsets" : False },
        { "offset_acc": [0xFFEC, 0x00A5, 0xFFE8] },
        { "offset_mag": [0xFFB4, 0xFE9E, 0x027D] },
        { "offset_gyr": [0x0002, 0xFFFF, 0xFFFF] }
    ],
    output='screen'
),
```

2022-12-12 02:26 UTC, flynneva requested changes
@asymingt overall awesome PR!!!! Love the work you did here and other than a few small comments everything looks great!

2022-12-12 02:26 UTC, flynneva commented on bno055/params/bno055_params.yaml
> +    connection_type: "i2c"
@asymingt instead of editing these in place, could we instead create a new file, so then we have one param file for UART and one param file for I2C?

2022-12-12 02:26 UTC, flynneva commented on bno055/params/NodeParameters.py
> +            self.i2c_bus = node.get_parameter('i2c_bus')
@asymingt these should be within a `if self.connection_type == I2C.CONNECTIONTYPE_I2C`, no? probably same for the UART-specific params as well

2022-12-12 02:26 UTC, flynneva commented on bno055/params/NodeParameters.py
> +        # UART port
@asymingt nit, but maybe we could update the comments here for the I2C-specific params they are related to

2022-12-12 02:26 UTC, flynneva commented on bno055/connectors/i2c.py
> +            raise TransmissionException('I2C not yet implemented')
@asymingt should this instead be an exception like:

```suggestion
            raise TransmissionException('Could not get BNO055 chip ID via I2C')
```

2022-12-12 02:27 UTC, flynneva commented
>>>
Worked out that we are bus limited -- it's either the i2c bus or the chip that is holding back the sampling frequency. Knowing this, I can get ~100Hz raw IMU and ~20Hz magnetometer with this PR, where I've separated our the publication into smaller i2c transactions.
>>>

@asymingt this might be something we can just add to the docs later so others know this as well for I2C. If you want to add it to this PR feel free, but also we can just add it in another PR later as well...not a big deal either way.

2022-12-27 03:42 UTC, asymingt commented
@flynneva I think I addressed your review comments. I added a couple of copyright headers to files that didn't have them. Hopefully that's OK.

2023-01-03 19:14 UTC, asymingt commented
@flynneva feel free to merge this when you're ready to add the changes.

2023-01-05 14:25 UTC, flynneva commented
@asymingt yes sorry! I am traveling for work this week (at CES) so I won't get to it this week but will make it a priority next week.

2023-01-14 02:51 UTC, flynneva approved these changes

2023-01-14 02:52 UTC, merged

2023-01-14 02:53 UTC, flynneva commented
@asymingt again, thank you for the contribution! 🙏🏼  stuff like this is what makes the ROS / OSS community so great 👏🏼

2023-01-19 12:17 UTC, emilnovak commented on bno055/connectors/uart.py
> +            buf_in = bytearray(self.serialConnection.read())
This line should be `buf_in = bytearray(self.serialConnection.read(2))` since the UART protocol register write answers with two bytes (preferably 0xEE 0X01 - Write success) which is tested later in line 140. Additional reasoning: previous implementation in bno055/connectors/Connector.py line 126 and [datasheet](https://cdn-shop.adafruit.com/datasheets/BST_BNO055_DS000_12.pdf) page 93.

2023-01-19 12:40 UTC, emilnovak commented on bno055/connectors/uart.py
> +            buf_in = bytearray(self.serialConnection.read())
https://github.com/flynneva/bno055/pull/57