Fix/flake8
flynneva/bno055 pull request #6
Opened 2021-01-18 22:38 UTC by flynneva

- fixed remaining flake8 errors including line length
- fixed remaining pep257 errors

have a look at the line length fixes, if you think they are too difficult to read or make the code less-readible lets discuss. i think all that is needed is an additional file that configures the max-line-length parameter for flake8 (filename .flake8 in in the root dir i think).

additionally, all thats left is to fix the copyright errors. i've moved the legacy copright notice to the `LEGACY_COPYRIGHT` file in the root directory.  there is a ROS2 tool for this called ament_copyright which can "auto-add" whatever license you want. I think we should keep the BSD3 clause license, and for the authors we can curate an `AUTHORS` file which lists all people who have contributed to the project. what do you think?

2021-01-19 01:13 UTC, flynneva commented
i've gone ahead and replaced all the `exceptions` with the single custom `TransmissionException` we have already defined. I think for most of the try/catches this works...but I could be wrong.

2021-01-19 07:31 UTC, whatis777 requested changes

2021-01-19 07:31 UTC, whatis777 commented on bno055/bno055.py
> +            except TransmissionException as e:
This is actually the only location in the stacktrace where we catch an exception in this stack . It should be a general one to get all of them not only the ones that we throw. We  never know what could happen - e.g. TypeErrors and so on

2021-01-19 07:31 UTC, whatis777 commented on bno055/bno055.py
> +            except TransmissionException as e:
This is actually the only location in the stacktrace where we catch an exception in this stack . It should be a general one to get all of them not only the ones that we throw. We  never know what could happen - e.g. TypeErrors and so on

2021-01-19 07:31 UTC, whatis777 commented on bno055/params/NodeParameters.py
> +    --ros-args --params-file <workspace>/src/bno055/bno055/params/bno055_params.yaml
This is a good example what I meant with readability impact ;-)

2021-01-19 07:31 UTC, whatis777 commented on bno055/params/NodeParameters.py
> +        except TransmissionException as e:
Also here I'd suggest to keep the general exception to get all of them not only the ones that we throw. We  never know what could happen - e.g. TypeErrors and so on

2021-01-23 16:37 UTC, flynneva commented on bno055/bno055.py
> +            except TransmissionException as e:
so I changed this because we were failing the flake8 tests that checks for bare try/excepts - [this is the flake8 rule](https://github.com/elijahandrews/flake8-blind-except) that is throwing the error without this change

2021-01-23 17:57 UTC, whatis777 commented on bno055/bno055.py
> +            except TransmissionException as e:
But in these cases we need a general exception handling as this is the only exception handling. If an exception is not handled here, the error will be handled in an uncontrolled way.
Furthermore the error handling at this location is the same for all errors: they will be logged but no more, so that the next cycle can be processed. So here it makes no sense to add specific error handling per exception type.

2021-01-26 18:11 UTC, flynneva commented on bno055/bno055.py
> +            except TransmissionException as e:
ok i agree. after doing some digging i think we can set flake8 to ignore specific lines of code for the `blind-except` errors. ill see if I can implement it and push an update here.

2021-01-26 18:20 UTC, flynneva commented on bno055/params/NodeParameters.py
> +    --ros-args --params-file <workspace>/src/bno055/bno055/params/bno055_params.yaml
we can come back to readability fixes later on i think if thats ok

2021-01-26 18:20 UTC, flynneva commented on bno055/params/NodeParameters.py
> +    --ros-args --params-file <workspace>/src/bno055/bno055/params/bno055_params.yaml
i would expect a whole PR will be needed to update the docs generation bit in the future

2021-01-26 20:16 UTC, whatis777 commented on bno055/bno055.py
> +            except TransmissionException as e:
great, thx for investigating, Evan!

2021-01-26 20:17 UTC, whatis777 commented on bno055/params/NodeParameters.py
> +    --ros-args --params-file <workspace>/src/bno055/bno055/params/bno055_params.yaml
Sounds good! Sure, let's revise the complete documentation in a separate PR

2021-01-26 20:19 UTC, whatis777 commented on bno055/bno055.py
> +            except Exception as e:  # noqa: B902
nice solution! If you have a link where we can read about this mechanism, feel free to add it to our QA section in the Readme

2021-01-26 20:20 UTC, whatis777 commented
LGTM

2021-01-26 20:21 UTC, whatis777 approved these changes

2021-01-26 20:51 UTC, merged